# test 6
name: 'Deploy blog'
on: 
  push:
    branches:
      - blog
jobs:
  generate-blog:
    name: 'Deploy to nettee.github.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup Hexo
        run: |
          npm install
          npm install -g hexo
          git clone https://github.com/nettee/hexo-theme-next themes/next
      - name: Build Hexo
        run: |
          hexo clean
          hexo generate
      - name: Push files
        run: |
          cd ./public
          git init
          git add .
          git commit -m "Deploy blog pages"
          git push --force --quiet "https://github.com/nettee/nettee.github.io" master:master

