# test 3
name: 'Deploy to nettee.github.io'
on: 
  push:
    branches:
      - blog
jobs:
  generate-blog:
    name: 'Generate blog files'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - run: git clone https://github.com/nettee/hexo-theme-next themes/next
